# Dataset - DataFrame

### 1. Preparar el entorno e importar la clase de carga
El notebook puede ejecutarse desde distintas carpetas. Por eso se buscan los directorios padres hasta encontrar src/clases_po y se agrega src a sys.path. Así se puede importar HFDatasetLoader sin instalar el proyecto como paquete.

In [1]:
import sys
import pandas as pd
from pathlib import Path

ROOT = Path.cwd().resolve()
while ROOT != ROOT.parent and not (ROOT / "src" / "clases_po").exists():
    ROOT = ROOT.parent

sys.path.insert(0, str(ROOT / "src"))

from clases_po import HFDatasetLoader

/workspaces/Machine-Learning-/.venv/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

### 2. Configurar el dataset y la salida
dataset_name identifica el repositorio en Hugging Face y split="train" indica la división que se descargará. El parámetro filename hace que el DataFrame también se guarde como CSV en src/carga_datos/datos/ cuando el notebook se ejecuta desde esa carpeta.

In [2]:
loader = HFDatasetLoader(
    dataset_name="0tizm0/video-games",
    split="train",
    filename="datos/video-games.csv",
    
)

### 3. Descargar el dataset y crear el DataFrame
El método load() descarga el dataset, lo convierte a pandas.DataFrame y lo asigna a la variable df. La expresión df.head() muestra las primeras filas para comprobar que la carga fue exitosa.

In [3]:
df = loader.load()
df.head()

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Repo card metadata block was not found. Setting CardData to empty.

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating,Year_missing,Is_Hit
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8.0,322.0,Nintendo,E,0.0,1.0
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN,Unknown,None,0.0,1.0
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E,0.0,1.0
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8.0,192.0,Nintendo,E,0.0,1.0
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,Unknown,None,0.0,1.0

## 4. Reducir el número de registros dataframe
Se reduce el número de registros a 5000 de 16713, para poder agilizar el tiempo de carga en herramienta jupyter,¿porque no se reduce mas el dataset?, para poder realizar los analisis correspondientes como lo desee el cliente y no tener sesgos en los datos

In [4]:
print(f"Número de registros en dataset original",df.shape) 

df2 = df[:5000] 
print(f"Nuevo dataset con los 5000 registros",df2.shape)

Número de registros en dataset original (16713, 18)
Nuevo dataset con los 5000 registros (5000, 18)

### 5. Revisar la estructura del DataFrame
Esta celda realiza una revisión inicial: cuenta filas y columnas y muestra el tipo de cada columna junto con información de memoria y valores no nulos. Esta inspección ayuda a detectar problemas antes de analizar los datos.

In [5]:
print(f"Filas: {len(df2)}")
print(f"Columnas: {len(df2.columns)}")
df2.info()

Filas: 5000
Columnas: 18
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             5000 non-null   object
 1   Platform         5000 non-null   object
 2   Year_of_Release  4931 non-null   float64
 3   Genre            5000 non-null   object
 4   Publisher        5000 non-null   object
 5   NA_Sales         5000 non-null   float64
 6   EU_Sales         5000 non-null   float64
 7   JP_Sales         5000 non-null   float64
 8   Other_Sales      5000 non-null   float64
 9   Global_Sales     5000 non-null   float64
 10  Critic_Score     3134 non-null   float64
 11  Critic_Count     3134 non-null   float64
 12  User_Score       3177 non-null   float64
 13  User_Count       3177 non-null   float64
 14  Developer        5000 non-null   object
 15  Rating           3461 non-null   object
 16  Year_missing     5000 non-null   float64
 17  Is_Hit           5000 non-null   float64
dtypes: float64(12), object(6)
memory usage: 703.3+ KB

In [6]:
df2.describe()

,Year_of_Release,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Year_missing,Is_Hit
count,4931.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,3134.000000,3134.00000,3177.000000,3177.000000,5000.000000,5000.000000
mean,2005.362604,0.738678,0.424764,0.193678,0.138650,1.495654,75.176452,35.68411,7.377494,279.101353,0.013800,0.841000
std,6.669261,1.370542,0.855385,0.539397,0.322828,2.582389,12.108450,22.01241,1.312181,782.361264,0.116672,0.365713
min,1980.000000,0.000000,0.000000,0.000000,0.000000,0.380000,20.000000,4.00000,0.000000,4.000000,0.000000,0.000000
25%,2002.000000,0.250000,0.090000,0.000000,0.030000,0.530000,69.000000,18.00000,6.700000,20.000000,0.000000,1.000000
50%,2007.000000,0.420000,0.210000,0.000000,0.070000,0.820000,77.000000,31.00000,7.700000,51.000000,0.000000,1.000000
75%,2010.000000,0.780000,0.450000,0.130000,0.140000,1.510000,84.000000,51.00000,8.300000,169.000000,0.000000,1.000000
max,2016.000000,41.360000,28.960000,10.220000,10.570000,82.530000,98.000000,113.00000,9.600000,10665.000000,1.000000,1.000000

In [ ]:
# 1. Ficha Técnica ajustada a df2
ficha_tecnica = pd.DataFrame({
    "Propiedad": [
        "Nombre del Dataset", "Repositorio / Identificador", "Enlace Directo",
        "Fecha de Consulta", "Licencia", "Procedencia", 
        "Datos Sintéticos", "Tamaño de Muestra", "Uso de Memoria"
    ],
    "Detalle": [
        "Video Game Sales with Ratings",
        "Kaggle (rush49/video-games-sales-with-ratings)",
        "https://www.kaggle.com/datasets/rush49/video-games-sales-with-ratings",
        "25 de octubre de 2026",
        "CC0: Public Domain",
        "Scraping de VGChartz y Metacritic",
        "No (incluye variables derivadas: Year_missing, Is_Hit)",
        f"{df2.shape[0]} filas × {df2.shape[1]} columnas",
        f"{df2.memory_usage(deep=True).sum() / 1024:.1f} KB"
    ]
})

# 2. Listado de variables para análisis
categoricas = ['Name', 'Platform', 'Genre', 'Publisher', 'Developer', 'Rating']
numericas = ['Year_of_Release', 'NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales', 
             'Global_Sales', 'Critic_Score', 'Critic_Count', 'User_Score', 'User_Count']

# 3. Función de auditoría e impresión de reporte
def auditar_df2(data):
    print("=== 1. FICHA TÉCNICA Y PROCEDENCIA ===")
    print(ficha_tecnica.to_string(index=False))
    
    print("\n=== 2. ESTRUCTURA Y TIPOS DE DATOS (df2) ===")
    data.info()
    
    print("\n=== 3. AUDITORÍA DE LIMITACIONES (VALORES FALTANTES EN df2) ===")
    missing_df = pd.DataFrame({
        'Completos': data.count(),
        'Faltantes': data.isnull().sum(),
        '% Faltantes': (data.isnull().sum() / len(data) * 100).round(2)
    })
    print(missing_df[missing_df['Faltantes'] > 0])

    cols_num_presentes = [col for col in numericas if col in data.columns]
    print("\n=== 4. RESUMEN DE VARIABLES NUMÉRICAS EN df2 ===")
    print(data[cols_num_presentes].describe().T[['mean', 'std', 'min', '50%', 'max']])

# Ejecución inmediata sobre df2
auditar_df2(df2)

=== 1. FICHA TÉCNICA Y PROCEDENCIA ===
                  Propiedad                                                               Detalle
         Nombre del Dataset                                         Video Game Sales with Ratings
Repositorio / Identificador                        Kaggle (rush49/video-games-sales-with-ratings)
             Enlace Directo https://www.kaggle.com/datasets/rush49/video-games-sales-with-ratings
          Fecha de Consulta                                                 25 de octubre de 2026
                   Licencia                                                    CC0: Public Domain
                Procedencia                                     Scraping de VGChartz y Metacritic
           Datos Sintéticos                No (incluye variables derivadas: Year_missing, Is_Hit)
          Tamaño de Muestra                                              5000 filas × 18 columnas
             Uso de Memoria                                                             2149.7 KB

=== 2. ESTRUCTURA Y TIPOS DE DATOS (df2) ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             5000 non-null   object
 1   Platform         5000 non-null   object
 2   Year_of_Release  4931 non-null   float64
 3   Genre            5000 non-null   object
 4   Publisher        5000 non-null   object
 5   NA_Sales         5000 non-null   float64
 6   EU_Sales         5000 non-null   float64
 7   JP_Sales         5000 non-null   float64
 8   Other_Sales      5000 non-null   float64
 9   Global_Sales     5000 non-null   float64
 10  Critic_Score     3134 non-null   float64
 11  Critic_Count     3134 non-null   float64
 12  User_Score       3177 non-null   float64
 13  User_Count       3177 non-null   float64
 14  Developer        5000 non-null   object
 15  Rating           3461 non-null   object
 16  Year_missing     5000 non-null   float64
 17  Is_Hit           5000 non-null   float64
dtypes: float64(12), object(6)
memory usage: 703.3+ KB

=== 3. AUDITORÍA DE LIMITACIONES (VALORES FALTANTES EN df2) ===
                 Completos  Faltantes  % Faltantes
Year_of_Release       4931         69         1.38
Critic_Score          3134       1866        37.32
Critic_Count          3134       1866        37.32
User_Score            3177       1823        36.46
User_Count            3177       1823        36.46
Rating                3461       1539        30.78

=== 4. RESUMEN DE VARIABLES NUMÉRICAS EN df2 ===
                        mean         std      min      50%       max
Year_of_Release  2005.362604    6.669261  1980.00  2007.00   2016.00
NA_Sales            0.738678    1.370542     0.00     0.42     41.36
EU_Sales            0.424764    0.855385     0.00     0.21     28.96
JP_Sales            0.193678    0.539397     0.00     0.00     10.22
Other_Sales         0.138650    0.322828     0.00     0.07     10.57
Global_Sales        1.495654    2.582389     0.38     0.82     82.53
Critic_Score       75.176452   12.108450    20.00    77.00     98.00
Critic_Count       35.684110   22.012410     4.00    31.00    113.00
User_Score          7.377494    1.312181     0.00     7.70      9.60
User_Count        279.101353  782.361264     4.00    51.00  10665.00

# Reporte

### 6. Importar la clase de reportes
Reportes recibe un DataFrame en sus métodos y permite generar un resumen textual, imprimirlo en la consola o guardarlo en un archivo .txt.

In [8]:
from clases_po import Reportes

### 7. Generar y visualizar el reporte como texto
generar_reporte(df) devuelve un str con el número de filas, columnas, duplicados, tipos de datos, valores nulos y estadísticas numéricas. En esta celda el texto se guarda temporalmente en texto y se imprime.

In [9]:
reportes = Reportes()
texto = reportes.generar_reporte(df2)

print(texto)

REPORTE DEL DATAFRAME
============================================================
Filas: 5000
Columnas: 18
Duplicados: 0

Columnas y tipos:
- Name: object
- Platform: object
- Year_of_Release: float64
- Genre: object
- Publisher: object
- NA_Sales: float64
- EU_Sales: float64
- JP_Sales: float64
- Other_Sales: float64
- Global_Sales: float64
- Critic_Score: float64
- Critic_Count: float64
- User_Score: float64
- User_Count: float64
- Developer: object
- Rating: object
- Year_missing: float64
- Is_Hit: float64

Valores nulos por columna:
- Name: 0
- Platform: 0
- Year_of_Release: 69
- Genre: 0
- Publisher: 0
- NA_Sales: 0
- EU_Sales: 0
- JP_Sales: 0
- Other_Sales: 0
- Global_Sales: 0
- Critic_Score: 1866
- Critic_Count: 1866
- User_Score: 1823
- User_Count: 1823
- Developer: 0
- Rating: 1539
- Year_missing: 0
- Is_Hit: 0

Estadísticas numéricas:
       Year_of_Release  NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales  Critic_Score  Critic_Count  User_Score  User_Count  Year_missing    Is_Hit
count         4931.000  5000.000  5000.000  5000.000     5000.000      5000.000      3134.000      3134.000    3177.000    3177.000      5000.000  5000.000
mean          2005.363     0.739     0.425     0.194        0.139         1.496        75.176        35.684       7.377     279.101         0.014     0.841
std              6.669     1.371     0.855     0.539        0.323         2.582        12.108        22.012       1.312     782.361         0.117     0.366
min           1980.000     0.000     0.000     0.000        0.000         0.380        20.000         4.000       0.000       4.000         0.000     0.000
25%           2002.000     0.250     0.090     0.000        0.030         0.530        69.000        18.000       6.700      20.000         0.000     1.000
50%           2007.000     0.420     0.210     0.000        0.070         0.820        77.000        31.000       7.700      51.000         0.000     1.000
75%           2010.000     0.780     0.450     0.130        0.140         1.510        84.000        51.000       8.300     169.000         0.000     1.000
max           2016.000    41.360    28.960    10.220       10.570        82.530        98.000       113.000       9.600   10665.000         1.000     1.000

### 8.Metadata descriptiva de `df2`
La tabla incluye tipo, longitud mínima, máxima y promedio en caracteres de los valores de cada columna, límites, conteos de nulos/no nulos, valores únicos, moda y frecuencia. En columnas numéricas también calcula rango, media, mediana, desviación estándar y cuartiles. Para texto, los límites son lexicográficos.

In [10]:
metadata_df2 = reportes.reporte_descriptivo(df2)
metadata_df2

,columna,tipo,longitud_minima_caracteres,longitud_maxima_caracteres,longitud_media_caracteres,valores_no_nulos,valores_nulos,porcentaje_nulos,valores_unicos,moda,frecuencia_moda,limite_inferior,limite_superior,rango,media,mediana,desviacion_estandar,cuartil_25,cuartil_75
0,Name,object,2,106,21.739000,5000,0,0.00,3539,FIFA 14,7,Fire Emblem Fates,wwe Smackdown vs. Raw 2006,NaN,NaN,NaN,NaN,NaN,NaN
1,Platform,object,2,4,2.889600,5000,0,0.00,26,PS2,803,2600,XOne,NaN,NaN,NaN,NaN,NaN,NaN
2,Year_of_Release,float64,6,6,6.000000,4931,69,1.38,37,2008.0,422,1980.0,2016.0,36.00,2005.362604,2007.00,6.669261,2002.00,2010.00
3,Genre,object,4,12,7.053600,5000,0,0.00,12,Action,1065,Action,Strategy,NaN,NaN,NaN,NaN,NaN,NaN
4,Publisher,object,3,38,13.831800,5000,0,0.00,194,Electronic Arts,779,20th Century Fox Video Games,"mixi, Inc",NaN,NaN,NaN,NaN,NaN,NaN
5,NA_Sales,float64,3,5,3.840200,5000,0,0.00,402,0.0,359,0.0,41.36,41.36,0.738678,0.42,1.370542,0.25,0.78
6,EU_Sales,float64,3,5,3.817200,5000,0,0.00,307,0.0,507,0.0,28.96,28.96,0.424764,0.21,0.855385,0.09,0.45
7,JP_Sales,float64,3,5,3.414600,5000,0,0.00,244,0.0,2766,0.0,10.22,10.22,0.193678,0.00,0.539397,0.00,0.13
8,Other_Sales,float64,3,5,3.880200,5000,0,0.00,155,0.04,420,0.0,10.57,10.57,0.138650,0.07,0.322828,0.03,0.14
9,Global_Sales,float64,3,5,3.906000,5000,0,0.00,592,0.42,108,0.38,82.53,82.15,1.495654,0.82,2.582389,0.53,1.51
10,Critic_Score,float64,4,4,4.000000,3134,1866,37.32,71,80.0,133,20.0,98.0,78.00,75.176452,77.00,12.108450,69.00,84.00
11,Critic_Count,float64,3,5,3.904914,3134,1866,37.32,104,18.0,72,4.0,113.0,109.00,35.684110,31.00,22.012410,18.00,51.00
12,User_Score,float64,3,3,3.000000,3177,1823,36.46,81,7.8,133,0.0,9.6,9.60,7.377494,7.70,1.312181,6.70,8.30
13,User_Count,float64,3,7,4.307208,3177,1823,36.46,744,6.0,72,4.0,10665.0,10661.00,279.101353,51.00,782.361264,20.00,169.00
14,Developer,object,2,60,11.373000,5000,0,0.00,729,Unknown,1524,1st Playable Productions,syn Sophia,NaN,NaN,NaN,NaN,NaN,NaN
15,Rating,object,1,4,1.393528,3461,1539,30.78,7,E,1315,AO,T,NaN,NaN,NaN,NaN,NaN,NaN
16,Year_missing,float64,3,3,3.000000,5000,0,0.00,2,0.0,4931,0.0,1.0,1.00,0.013800,0.00,0.116672,0.00,0.00
17,Is_Hit,float64,3,3,3.000000,5000,0,0.00,2,1.0,4205,0.0,1.0,1.00,0.841000,1.00,0.365713,1.00,1.00

### 8. Imprimir el reporte directamente
imprimir_reporte(df) ejecuta la generación y muestra el resultado directamente. Es útil para consultar rápidamente el resumen durante una ejecución interactiva.

In [11]:
reportes.imprimir_reporte(df2)

REPORTE DEL DATAFRAME
============================================================
Filas: 5000
Columnas: 18
Duplicados: 0

Columnas y tipos:
- Name: object
- Platform: object
- Year_of_Release: float64
- Genre: object
- Publisher: object
- NA_Sales: float64
- EU_Sales: float64
- JP_Sales: float64
- Other_Sales: float64
- Global_Sales: float64
- Critic_Score: float64
- Critic_Count: float64
- User_Score: float64
- User_Count: float64
- Developer: object
- Rating: object
- Year_missing: float64
- Is_Hit: float64

Valores nulos por columna:
- Name: 0
- Platform: 0
- Year_of_Release: 69
- Genre: 0
- Publisher: 0
- NA_Sales: 0
- EU_Sales: 0
- JP_Sales: 0
- Other_Sales: 0
- Global_Sales: 0
- Critic_Score: 1866
- Critic_Count: 1866
- User_Score: 1823
- User_Count: 1823
- Developer: 0
- Rating: 1539
- Year_missing: 0
- Is_Hit: 0

Estadísticas numéricas:
       Year_of_Release  NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales  Critic_Score  Critic_Count  User_Score  User_Count  Year_missing    Is_Hit
count         4931.000  5000.000  5000.000  5000.000     5000.000      5000.000      3134.000      3134.000    3177.000    3177.000      5000.000  5000.000
mean          2005.363     0.739     0.425     0.194        0.139         1.496        75.176        35.684       7.377     279.101         0.014     0.841
std              6.669     1.371     0.855     0.539        0.323         2.582        12.108        22.012       1.312     782.361         0.117     0.366
min           1980.000     0.000     0.000     0.000        0.000         0.380        20.000         4.000       0.000       4.000         0.000     0.000
25%           2002.000     0.250     0.090     0.000        0.030         0.530        69.000        18.000       6.700      20.000         0.000     1.000
50%           2007.000     0.420     0.210     0.000        0.070         0.820        77.000        31.000       7.700      51.000         0.000     1.000
75%           2010.000     0.780     0.450     0.130        0.140         1.510        84.000        51.000       8.300     169.000         0.000     1.000
max           2016.000    41.360    28.960    10.220       10.570        82.530        98.000       113.000       9.600   10665.000         1.000     1.000

### 9. Guardar el reporte en un archivo de texto
guardar_reporte(df, ruta) crea los directorios necesarios y escribe el reporte en UTF-8. El archivo quedará en src/sincronicas/reportes/fast_food_restaurants.txt cuando se ejecute desde src/sincronicas.

In [12]:
ruta = reportes.guardar_reporte(
    df2,
    "reportes/video-games.txt",
)

print(f"Reporte guardado en: {ruta}")

Reporte guardado en: reportes/video-games.txt

# Transformaciones

### 10. Transformación 1: Traducir y estandarizar nombres de columnas
Se renombran las 18 columnas del DataFrame de inglés a español manteniendo el formato `snake_case` para mejorar la legibilidad del análisis.

In [13]:
# Diccionario de traducción de columnas para el dataset de videojuegos
columnas_espanol = {
    'Name': 'nombre',
    'Platform': 'plataforma',
    'Year_of_Release': 'anio_lanzamiento',
    'Genre': 'genero',
    'Publisher': 'editor',
    'NA_Sales': 'ventas_na',
    'EU_Sales': 'ventas_eu',
    'JP_Sales': 'ventas_jp',
    'Other_Sales': 'ventas_otros',
    'Global_Sales': 'ventas_globales',
    'Critic_Score': 'puntuacion_critica',
    'Critic_Count': 'cantidad_criticas',
    'User_Score': 'puntuacion_usuario',
    'User_Count': 'cantidad_usuarios',
    'Developer': 'desarrollador',
    'Rating': 'clasificacion',
    'Year_missing': 'anio_faltante',
    'Is_Hit': 'es_exito'
}

# Aplicar el renombrado
df2 = df2.rename(columns=columnas_espanol)

# Mostrar las primeras filas con los nuevos nombres
df2.head()

,nombre,plataforma,anio_lanzamiento,genero,editor,ventas_na,ventas_eu,ventas_jp,ventas_otros,ventas_globales,puntuacion_critica,cantidad_criticas,puntuacion_usuario,cantidad_usuarios,desarrollador,clasificacion,anio_faltante,es_exito
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8.0,322.0,Nintendo,E,0.0,1.0
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN,Unknown,None,0.0,1.0
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E,0.0,1.0
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8.0,192.0,Nintendo,E,0.0,1.0
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,Unknown,None,0.0,1.0

### 11 Transformación 2: Cálculo de la antigüedad del juego en años
Se crea una nueva variable calculada restando el año de lanzamiento al año actual para expresar la antigüedad de cada título en años.

In [14]:
# Definir año de referencia / actual
anio_actual = 2026

# Operación matemática directa sobre la columna
df2['antiguedad_anios'] = anio_actual - df2['anio_lanzamiento']

# Mostrar resultado
df2[['nombre', 'anio_lanzamiento', 'antiguedad_anios']].head()

/tmp/ipykernel_54820/2567294891.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df2['antiguedad_anios'] = anio_actual - df2['anio_lanzamiento']

                     nombre  anio_lanzamiento  antiguedad_anios
0                Wii Sports            2006.0              20.0
1         Super Mario Bros.            1985.0              41.0
2            Mario Kart Wii            2008.0              18.0
3         Wii Sports Resort            2009.0              17.0
4  Pokemon Red/Pokemon Blue            1996.0              30.0

### 12. Transformación 3: Porcentaje de ventas regionales sobre el total global
Se calcula la proporción porcentual de las ventas de Norteamérica y Japón en relación con las ventas globales del título.

In [15]:
# Calcular porcentaje de ventas por región respecto al global
df2['pct_ventas_na'] = ((df2['ventas_na'] / df2['ventas_globales']) * 100).round(2)
df2['pct_ventas_jp'] = ((df2['ventas_jp'] / df2['ventas_globales']) * 100).round(2)

# Mostrar resultado
df2[['nombre', 'ventas_globales', 'pct_ventas_na', 'pct_ventas_jp']].head()

/tmp/ipykernel_54820/1493007039.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df2['pct_ventas_na'] = ((df2['ventas_na'] / df2['ventas_globales']) * 100).round(2)
/tmp/ipykernel_54820/1493007039.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df2['pct_ventas_jp'] = ((df2['ventas_jp'] / df2['ventas_globales']) * 100).round(2)

                     nombre  ventas_globales  pct_ventas_na  pct_ventas_jp
0                Wii Sports            82.53          50.12           4.57
1         Super Mario Bros.            40.24          72.27          16.92
2            Mario Kart Wii            35.52          44.14          10.67
3         Wii Sports Resort            32.77          47.64          10.01
4  Pokemon Red/Pokemon Blue            31.37          35.93          32.58

### 13. Transformación 4: Agrupamiento por Género de Videojuego
Se agrupan los datos según el género para calcular el promedio de ventas globales, el promedio de puntuación de la crítica, el promedio de puntuación de los usuarios y la cantidad total de juegos por género.

In [16]:
# Agrupamiento por género y cálculo de promedios/métricas
df_resumen = df2.groupby('genero').agg({
    'ventas_globales': 'mean',
    'puntuacion_critica': 'mean',
    'puntuacion_usuario': 'mean',
    'nombre': 'count'
}).rename(columns={
    'ventas_globales': 'Ventas Globales Promedio',
    'puntuacion_critica': 'Puntuación Crítica Promedio',
    'puntuacion_usuario': 'Puntuación Usuario Promedio',
    'nombre': 'Total de Videojuegos'
}).reset_index()

df_resumen

,genero,Ventas Globales Promedio,Puntuación Crítica Promedio,Puntuación Usuario Promedio,Total de Videojuegos
0,Action,1.358808,73.311409,7.355844,1065
1,Adventure,1.091429,72.423729,7.435088,133
2,Fighting,1.309929,76.131429,7.720000,282
3,Misc,1.408512,71.248869,6.988571,457
4,Platform,2.068306,72.330097,7.621182,366
5,Puzzle,1.602602,73.754717,7.775610,123
6,Racing,1.528378,73.402256,7.430620,407
7,Role-Playing,1.732888,78.440559,7.820890,464
8,Shooter,1.798192,77.344498,7.274707,531
9,Simulation,1.316582,72.719424,7.319048,237
10,Sports,1.351337,78.384466,7.132288,823
11,Strategy,1.014643,79.803922,7.587273,112