# Dataset - DataFrame

### 1. Preparar el entorno e importar la clase de carga
El notebook puede ejecutarse desde distintas carpetas. Por eso se buscan los directorios padres hasta encontrar src/clases_po y se agrega src a sys.path. Así se puede importar HFDatasetLoader sin instalar el proyecto como paquete.

In [1]:
import sys
from pathlib import Path

ROOT = Path.cwd().resolve()
while ROOT != ROOT.parent and not (ROOT / "src" / "clases_po").exists():
    ROOT = ROOT.parent

sys.path.insert(0, str(ROOT / "src"))

from clases_po import HFDatasetLoader

/home/runner/work/Machine-Learning-/Machine-Learning-/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

### 2. Configurar el dataset y la salida
dataset_name identifica el repositorio en Hugging Face y split="train" indica la división que se descargará. El parámetro filename hace que el DataFrame también se guarde como CSV en src/carga_datos/datos/ cuando el notebook se ejecuta desde esa carpeta.

In [2]:
loader = HFDatasetLoader(
    dataset_name="0tizm0/video-games",
    split="train",
    filename="datos/video-games.csv",
    
)

### 3. Descargar el dataset y crear el DataFrame
El método load() descarga el dataset, lo convierte a pandas.DataFrame y lo asigna a la variable df. La expresión df.head() muestra las primeras filas para comprobar que la carga fue exitosa.

In [3]:
df = loader.load()
df.head()

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Repo card metadata block was not found. Setting CardData to empty.

Generating train split:   0%|          | 0/16713 [00:00<?, ? examples/s]

Generating train split: 100%|██████████| 16713/16713 [00:00<00:00, 335278.71 examples/s]

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating,Year_missing,Is_Hit
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8.0,322.0,Nintendo,E,0.0,1.0
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN,Unknown,None,0.0,1.0
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E,0.0,1.0
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8.0,192.0,Nintendo,E,0.0,1.0
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,Unknown,None,0.0,1.0

### 4. Revisar la estructura del DataFrame
Esta celda realiza una revisión inicial: cuenta filas y columnas y muestra el tipo de cada columna junto con información de memoria y valores no nulos. Esta inspección ayuda a detectar problemas antes de analizar los datos.

In [4]:
print(f"Filas: {len(df)}")
print(f"Columnas: {len(df.columns)}")
df.info()

Filas: 16713
Columnas: 18
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16713 entries, 0 to 16712
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             16713 non-null  object
 1   Platform         16713 non-null  object
 2   Year_of_Release  16444 non-null  float64
 3   Genre            16713 non-null  object
 4   Publisher        16713 non-null  object
 5   NA_Sales         16713 non-null  float64
 6   EU_Sales         16713 non-null  float64
 7   JP_Sales         16713 non-null  float64
 8   Other_Sales      16713 non-null  float64
 9   Global_Sales     16713 non-null  float64
 10  Critic_Score     8137 non-null   float64
 11  Critic_Count     8137 non-null   float64
 12  User_Score       7590 non-null   float64
 13  User_Count       7590 non-null   float64
 14  Developer        16713 non-null  object
 15  Rating           9949 non-null   object
 16  Year_missing     16713 non-null  float64
 17  Is_Hit           16713 non-null  float64
dtypes: float64(12), object(6)
memory usage: 2.3+ MB

# Reporte

### 5. Importar la clase de reportes
Reportes recibe un DataFrame en sus métodos y permite generar un resumen textual, imprimirlo en la consola o guardarlo en un archivo .txt.

In [5]:
from clases_po import Reportes

### 6. Generar y visualizar el reporte como texto
generar_reporte(df) devuelve un str con el número de filas, columnas, duplicados, tipos de datos, valores nulos y estadísticas numéricas. En esta celda el texto se guarda temporalmente en texto y se imprime.

In [6]:
reportes = Reportes()
texto = reportes.generar_reporte(df)

print(texto)

REPORTE DEL DATAFRAME
============================================================
Filas: 16713
Columnas: 18
Duplicados: 0

Columnas y tipos:
- Name: object
- Platform: object
- Year_of_Release: float64
- Genre: object
- Publisher: object
- NA_Sales: float64
- EU_Sales: float64
- JP_Sales: float64
- Other_Sales: float64
- Global_Sales: float64
- Critic_Score: float64
- Critic_Count: float64
- User_Score: float64
- User_Count: float64
- Developer: object
- Rating: object
- Year_missing: float64
- Is_Hit: float64

Valores nulos por columna:
- Name: 0
- Platform: 0
- Year_of_Release: 269
- Genre: 0
- Publisher: 0
- NA_Sales: 0
- EU_Sales: 0
- JP_Sales: 0
- Other_Sales: 0
- Global_Sales: 0
- Critic_Score: 8576
- Critic_Count: 8576
- User_Score: 9123
- User_Count: 9123
- Developer: 0
- Rating: 6764
- Year_missing: 0
- Is_Hit: 0

Estadísticas numéricas:
       Year_of_Release   NA_Sales   EU_Sales   JP_Sales  Other_Sales  Global_Sales  Critic_Score  Critic_Count  User_Score  User_Count  Year_missing     Is_Hit
count        16444.000  16713.000  16713.000  16713.000    16713.000     16713.000      8137.000      8137.000    7590.000    7590.000     16713.000  16713.000
mean          2006.486      0.263      0.145      0.078        0.047         0.534        68.968        26.361       7.125     162.230         0.016      0.252
std              5.876      0.814      0.503      0.309        0.187         1.548        13.938        18.980       1.500     561.282         0.126      0.434
min           1980.000      0.000      0.000      0.000        0.000         0.010        13.000         3.000       0.000       4.000         0.000      0.000
25%           2003.000      0.000      0.000      0.000        0.000         0.060        60.000        12.000       6.400      10.000         0.000      0.000
50%           2007.000      0.080      0.020      0.000        0.010         0.170        71.000        21.000       7.500      24.000         0.000      0.000
75%           2010.000      0.240      0.110      0.040        0.030         0.470        79.000        36.000       8.200      81.000         0.000      1.000
max           2016.000     41.360     28.960     10.220       10.570        82.530        98.000       113.000       9.700   10665.000         1.000      1.000

### 7. Imprimir el reporte directamente
imprimir_reporte(df) ejecuta la generación y muestra el resultado directamente. Es útil para consultar rápidamente el resumen durante una ejecución interactiva.

In [7]:
reportes.imprimir_reporte(df)

REPORTE DEL DATAFRAME
============================================================
Filas: 16713
Columnas: 18
Duplicados: 0

Columnas y tipos:
- Name: object
- Platform: object
- Year_of_Release: float64
- Genre: object
- Publisher: object
- NA_Sales: float64
- EU_Sales: float64
- JP_Sales: float64
- Other_Sales: float64
- Global_Sales: float64
- Critic_Score: float64
- Critic_Count: float64
- User_Score: float64
- User_Count: float64
- Developer: object
- Rating: object
- Year_missing: float64
- Is_Hit: float64

Valores nulos por columna:
- Name: 0
- Platform: 0
- Year_of_Release: 269
- Genre: 0
- Publisher: 0
- NA_Sales: 0
- EU_Sales: 0
- JP_Sales: 0
- Other_Sales: 0
- Global_Sales: 0
- Critic_Score: 8576
- Critic_Count: 8576
- User_Score: 9123
- User_Count: 9123
- Developer: 0
- Rating: 6764
- Year_missing: 0
- Is_Hit: 0

Estadísticas numéricas:
       Year_of_Release   NA_Sales   EU_Sales   JP_Sales  Other_Sales  Global_Sales  Critic_Score  Critic_Count  User_Score  User_Count  Year_missing     Is_Hit
count        16444.000  16713.000  16713.000  16713.000    16713.000     16713.000      8137.000      8137.000    7590.000    7590.000     16713.000  16713.000
mean          2006.486      0.263      0.145      0.078        0.047         0.534        68.968        26.361       7.125     162.230         0.016      0.252
std              5.876      0.814      0.503      0.309        0.187         1.548        13.938        18.980       1.500     561.282         0.126      0.434
min           1980.000      0.000      0.000      0.000        0.000         0.010        13.000         3.000       0.000       4.000         0.000      0.000
25%           2003.000      0.000      0.000      0.000        0.000         0.060        60.000        12.000       6.400      10.000         0.000      0.000
50%           2007.000      0.080      0.020      0.000        0.010         0.170        71.000        21.000       7.500      24.000         0.000      0.000
75%           2010.000      0.240      0.110      0.040        0.030         0.470        79.000        36.000       8.200      81.000         0.000      1.000
max           2016.000     41.360     28.960     10.220       10.570        82.530        98.000       113.000       9.700   10665.000         1.000      1.000

### 8. Guardar el reporte en un archivo de texto
guardar_reporte(df, ruta) crea los directorios necesarios y escribe el reporte en UTF-8. El archivo quedará en src/sincronicas/reportes/fast_food_restaurants.txt cuando se ejecute desde src/sincronicas.

In [8]:
ruta = reportes.guardar_reporte(
    df,
    "reportes/video-games.txt",
)

print(f"Reporte guardado en: {ruta}")

Reporte guardado en: reportes/video-games.txt

# Transformaciones

### 9. Transformación 1: Traducir y estandarizar nombres de columnas
Se renombran las 18 columnas del DataFrame de inglés a español manteniendo el formato `snake_case` para mejorar la legibilidad del análisis.

In [9]:
# Diccionario de traducción de columnas para el dataset de videojuegos
columnas_espanol = {
    'Name': 'nombre',
    'Platform': 'plataforma',
    'Year_of_Release': 'anio_lanzamiento',
    'Genre': 'genero',
    'Publisher': 'editor',
    'NA_Sales': 'ventas_na',
    'EU_Sales': 'ventas_eu',
    'JP_Sales': 'ventas_jp',
    'Other_Sales': 'ventas_otros',
    'Global_Sales': 'ventas_globales',
    'Critic_Score': 'puntuacion_critica',
    'Critic_Count': 'cantidad_criticas',
    'User_Score': 'puntuacion_usuario',
    'User_Count': 'cantidad_usuarios',
    'Developer': 'desarrollador',
    'Rating': 'clasificacion',
    'Year_missing': 'anio_faltante',
    'Is_Hit': 'es_exito'
}

# Aplicar el renombrado
df = df.rename(columns=columnas_espanol)

# Mostrar las primeras filas con los nuevos nombres
df.head()

,nombre,plataforma,anio_lanzamiento,genero,editor,ventas_na,ventas_eu,ventas_jp,ventas_otros,ventas_globales,puntuacion_critica,cantidad_criticas,puntuacion_usuario,cantidad_usuarios,desarrollador,clasificacion,anio_faltante,es_exito
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8.0,322.0,Nintendo,E,0.0,1.0
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN,Unknown,None,0.0,1.0
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E,0.0,1.0
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8.0,192.0,Nintendo,E,0.0,1.0
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,Unknown,None,0.0,1.0

### 10. Transformación 2: Cálculo de la antigüedad del juego en años
Se crea una nueva variable calculada restando el año de lanzamiento al año actual para expresar la antigüedad de cada título en años.

In [10]:
# Definir año de referencia / actual
anio_actual = 2026

# Operación matemática directa sobre la columna
df['antiguedad_anios'] = anio_actual - df['anio_lanzamiento']

# Mostrar resultado
df[['nombre', 'anio_lanzamiento', 'antiguedad_anios']].head()

                     nombre  anio_lanzamiento  antiguedad_anios
0                Wii Sports            2006.0              20.0
1         Super Mario Bros.            1985.0              41.0
2            Mario Kart Wii            2008.0              18.0
3         Wii Sports Resort            2009.0              17.0
4  Pokemon Red/Pokemon Blue            1996.0              30.0

### 11. Transformación 3: Porcentaje de ventas regionales sobre el total global
Se calcula la proporción porcentual de las ventas de Norteamérica y Japón en relación con las ventas globales del título.

In [11]:
# Calcular porcentaje de ventas por región respecto al global
df['pct_ventas_na'] = ((df['ventas_na'] / df['ventas_globales']) * 100).round(2)
df['pct_ventas_jp'] = ((df['ventas_jp'] / df['ventas_globales']) * 100).round(2)

# Mostrar resultado
df[['nombre', 'ventas_globales', 'pct_ventas_na', 'pct_ventas_jp']].head()

                     nombre  ventas_globales  pct_ventas_na  pct_ventas_jp
0                Wii Sports            82.53          50.12           4.57
1         Super Mario Bros.            40.24          72.27          16.92
2            Mario Kart Wii            35.52          44.14          10.67
3         Wii Sports Resort            32.77          47.64          10.01
4  Pokemon Red/Pokemon Blue            31.37          35.93          32.58

### 12. Transformación 4: Agrupamiento por Género de Videojuego
Se agrupan los datos según el género para calcular el promedio de ventas globales, el promedio de puntuación de la crítica, el promedio de puntuación de los usuarios y la cantidad total de juegos por género.

In [12]:
# Agrupamiento por género y cálculo de promedios/métricas
df_resumen = df.groupby('genero').agg({
    'ventas_globales': 'mean',
    'puntuacion_critica': 'mean',
    'puntuacion_usuario': 'mean',
    'nombre': 'count'
}).rename(columns={
    'ventas_globales': 'Ventas Globales Promedio',
    'puntuacion_critica': 'Puntuación Crítica Promedio',
    'puntuacion_usuario': 'Puntuación Usuario Promedio',
    'nombre': 'Total de Videojuegos'
}).reset_index()

df_resumen

,genero,Ventas Globales Promedio,Puntuación Crítica Promedio,Puntuación Usuario Promedio,Total de Videojuegos
0,Action,0.518035,66.629101,7.054044,3369
1,Adventure,0.182417,65.331269,7.133000,1303
2,Fighting,0.527067,69.217604,7.302506,849
3,Misc,0.458960,66.619503,6.819362,1750
4,Platform,0.932523,68.058350,7.301402,888
5,Puzzle,0.419000,67.424107,7.175000,580
6,Racing,0.583587,67.963612,7.036193,1249
7,Role-Playing,0.623732,72.652646,7.619515,1498
8,Shooter,0.795873,70.181144,7.041883,1323
9,Simulation,0.446884,68.619318,7.134593,873
10,Sports,0.567291,71.968174,6.961197,2348
11,Strategy,0.255490,72.086093,7.295177,683