# Dataset - DataFrame

### 1. Preparar el entorno e importar la clase de carga
El notebook puede ejecutarse desde distintas carpetas. Por eso se buscan los directorios padres hasta encontrar src/clases_po y se agrega src a sys.path. Así se puede importar HFDatasetLoader sin instalar el proyecto como paquete.

In [35]:
import sys
from pathlib import Path

ROOT = Path.cwd().resolve()
while ROOT != ROOT.parent and not (ROOT / "src" / "clases_po").exists():
    ROOT = ROOT.parent

sys.path.insert(0, str(ROOT / "src"))

from clases_po import HFDatasetLoader

### 2. Configurar el dataset y la salida
dataset_name identifica el repositorio en Hugging Face y split="train" indica la división que se descargará. El parámetro filename hace que el DataFrame también se guarde como CSV en src/carga_datos/datos/ cuando el notebook se ejecuta desde esa carpeta.

In [36]:
loader = HFDatasetLoader(
    dataset_name="0tizm0/video-games",
    split="train",
    filename="datos/video-games.csv",
    
)

### 3. Descargar el dataset y crear el DataFrame
El método load() descarga el dataset, lo convierte a pandas.DataFrame y lo asigna a la variable df. La expresión df.head() muestra las primeras filas para comprobar que la carga fue exitosa.

In [37]:
df = loader.load()
df.head()

Repo card metadata block was not found. Setting CardData to empty.

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating,Year_missing,Is_Hit
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8.0,322.0,Nintendo,E,0.0,1.0
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN,Unknown,None,0.0,1.0
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E,0.0,1.0
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8.0,192.0,Nintendo,E,0.0,1.0
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,Unknown,None,0.0,1.0

### 4. Revisar la estructura del DataFrame
Esta celda realiza una revisión inicial: cuenta filas y columnas y muestra el tipo de cada columna junto con información de memoria y valores no nulos. Esta inspección ayuda a detectar problemas antes de analizar los datos.

In [38]:
print(f"Filas: {len(df)}")
print(f"Columnas: {len(df.columns)}")
df.info()

Filas: 16713
Columnas: 18
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16713 entries, 0 to 16712
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             16713 non-null  object
 1   Platform         16713 non-null  object
 2   Year_of_Release  16444 non-null  float64
 3   Genre            16713 non-null  object
 4   Publisher        16713 non-null  object
 5   NA_Sales         16713 non-null  float64
 6   EU_Sales         16713 non-null  float64
 7   JP_Sales         16713 non-null  float64
 8   Other_Sales      16713 non-null  float64
 9   Global_Sales     16713 non-null  float64
 10  Critic_Score     8137 non-null   float64
 11  Critic_Count     8137 non-null   float64
 12  User_Score       7590 non-null   float64
 13  User_Count       7590 non-null   float64
 14  Developer        16713 non-null  object
 15  Rating           9949 non-null   object
 16  Year_missing     16713 non-null  float64
 17  Is_Hit           16713 non-null  float64
dtypes: float64(12), object(6)
memory usage: 2.3+ MB

# Reporte

### 5. Importar la clase de reportes
Reportes recibe un DataFrame en sus métodos y permite generar un resumen textual, imprimirlo en la consola o guardarlo en un archivo .txt.

In [39]:
from clases_po import Reportes

### 6. Generar y visualizar el reporte como texto
generar_reporte(df) devuelve un str con el número de filas, columnas, duplicados, tipos de datos, valores nulos y estadísticas numéricas. En esta celda el texto se guarda temporalmente en texto y se imprime.

In [40]:
reportes = Reportes()
texto = reportes.generar_reporte(df)

print(texto)

REPORTE DEL DATAFRAME
============================================================
Filas: 16713
Columnas: 18
Duplicados: 0

Columnas y tipos:
- Name: object
- Platform: object
- Year_of_Release: float64
- Genre: object
- Publisher: object
- NA_Sales: float64
- EU_Sales: float64
- JP_Sales: float64
- Other_Sales: float64
- Global_Sales: float64
- Critic_Score: float64
- Critic_Count: float64
- User_Score: float64
- User_Count: float64
- Developer: object
- Rating: object
- Year_missing: float64
- Is_Hit: float64

Valores nulos por columna:
- Name: 0
- Platform: 0
- Year_of_Release: 269
- Genre: 0
- Publisher: 0
- NA_Sales: 0
- EU_Sales: 0
- JP_Sales: 0
- Other_Sales: 0
- Global_Sales: 0
- Critic_Score: 8576
- Critic_Count: 8576
- User_Score: 9123
- User_Count: 9123
- Developer: 0
- Rating: 6764
- Year_missing: 0
- Is_Hit: 0

Estadísticas numéricas:
       Year_of_Release   NA_Sales   EU_Sales   JP_Sales  Other_Sales  Global_Sales  Critic_Score  Critic_Count  User_Score  User_Count  Year_missing     Is_Hit
count        16444.000  16713.000  16713.000  16713.000    16713.000     16713.000      8137.000      8137.000    7590.000    7590.000     16713.000  16713.000
mean          2006.486      0.263      0.145      0.078        0.047         0.534        68.968        26.361       7.125     162.230         0.016      0.252
std              5.876      0.814      0.503      0.309        0.187         1.548        13.938        18.980       1.500     561.282         0.126      0.434
min           1980.000      0.000      0.000      0.000        0.000         0.010        13.000         3.000       0.000       4.000         0.000      0.000
25%           2003.000      0.000      0.000      0.000        0.000         0.060        60.000        12.000       6.400      10.000         0.000      0.000
50%           2007.000      0.080      0.020      0.000        0.010         0.170        71.000        21.000       7.500      24.000         0.000      0.000
75%           2010.000      0.240      0.110      0.040        0.030         0.470        79.000        36.000       8.200      81.000         0.000      1.000
max           2016.000     41.360     28.960     10.220       10.570        82.530        98.000       113.000       9.700   10665.000         1.000      1.000

### 7. Imprimir el reporte directamente
imprimir_reporte(df) ejecuta la generación y muestra el resultado directamente. Es útil para consultar rápidamente el resumen durante una ejecución interactiva.

In [41]:
reportes.imprimir_reporte(df)

REPORTE DEL DATAFRAME
============================================================
Filas: 16713
Columnas: 18
Duplicados: 0

Columnas y tipos:
- Name: object
- Platform: object
- Year_of_Release: float64
- Genre: object
- Publisher: object
- NA_Sales: float64
- EU_Sales: float64
- JP_Sales: float64
- Other_Sales: float64
- Global_Sales: float64
- Critic_Score: float64
- Critic_Count: float64
- User_Score: float64
- User_Count: float64
- Developer: object
- Rating: object
- Year_missing: float64
- Is_Hit: float64

Valores nulos por columna:
- Name: 0
- Platform: 0
- Year_of_Release: 269
- Genre: 0
- Publisher: 0
- NA_Sales: 0
- EU_Sales: 0
- JP_Sales: 0
- Other_Sales: 0
- Global_Sales: 0
- Critic_Score: 8576
- Critic_Count: 8576
- User_Score: 9123
- User_Count: 9123
- Developer: 0
- Rating: 6764
- Year_missing: 0
- Is_Hit: 0

Estadísticas numéricas:
       Year_of_Release   NA_Sales   EU_Sales   JP_Sales  Other_Sales  Global_Sales  Critic_Score  Critic_Count  User_Score  User_Count  Year_missing     Is_Hit
count        16444.000  16713.000  16713.000  16713.000    16713.000     16713.000      8137.000      8137.000    7590.000    7590.000     16713.000  16713.000
mean          2006.486      0.263      0.145      0.078        0.047         0.534        68.968        26.361       7.125     162.230         0.016      0.252
std              5.876      0.814      0.503      0.309        0.187         1.548        13.938        18.980       1.500     561.282         0.126      0.434
min           1980.000      0.000      0.000      0.000        0.000         0.010        13.000         3.000       0.000       4.000         0.000      0.000
25%           2003.000      0.000      0.000      0.000        0.000         0.060        60.000        12.000       6.400      10.000         0.000      0.000
50%           2007.000      0.080      0.020      0.000        0.010         0.170        71.000        21.000       7.500      24.000         0.000      0.000
75%           2010.000      0.240      0.110      0.040        0.030         0.470        79.000        36.000       8.200      81.000         0.000      1.000
max           2016.000     41.360     28.960     10.220       10.570        82.530        98.000       113.000       9.700   10665.000         1.000      1.000

### 8. Guardar el reporte en un archivo de texto
guardar_reporte(df, ruta) crea los directorios necesarios y escribe el reporte en UTF-8. El archivo quedará en src/sincronicas/reportes/fast_food_restaurants.txt cuando se ejecute desde src/sincronicas.

In [42]:
ruta = reportes.guardar_reporte(
    df,
    "reportes/fast_food_restaurants.txt",
)

print(f"Reporte guardado en: {ruta}")

Reporte guardado en: reportes/fast_food_restaurants.txt

# Transformaciones

### 9. Transformación 1: Traducir y estandarizar nombres de columnas
Se renombran las 13 columnas del DataFrame de inglés a español manteniendo el formato `snake_case` para mejorar la legibilidad del análisis.

In [43]:
# Diccionario de traducción de columnas
columnas_espanol = {
    'age': 'edad',
    'has_anaemia': 'tiene_anemia',
    'creatinine_phosphokinase_concentration_in_blood': 'cpk_sangre',
    'has_diabetes': 'tiene_diabetes',
    'heart_ejection_fraction': 'fraccion_eyeccion',
    'has_high_blood_pressure': 'tiene_hipertension',
    'platelets_concentration_in_blood': 'concentracion_plaquetas',
    'serum_creatinine_concentration_in_blood': 'creatinina_serica',
    'serum_sodium_concentration_in_blood': 'sodio_serico',
    'is_male': 'es_hombre',
    'is_smoker': 'es_fumador',
    'days_in_study': 'dias_seguimiento',
    'is_dead': 'fallecido'
}

# Aplicar el renombrado
df = df.rename(columns=columnas_espanol)

# Mostrar las primeras filas con los nuevos nombres
df.head()

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating,Year_missing,Is_Hit
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8.0,322.0,Nintendo,E,0.0,1.0
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN,Unknown,None,0.0,1.0
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E,0.0,1.0
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8.0,192.0,Nintendo,E,0.0,1.0
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,Unknown,None,0.0,1.0

### 10. Transformación 2: Conversión de días a años de seguimiento
Se crea una nueva variable calculada dividiendo los días de seguimiento entre 365 para expresar el tiempo en años.

In [44]:
# Operación matemática directa sobre la columna
df['anos_seguimiento'] = (df['dias_seguimiento'] / 365).round(2)

# Mostrar resultado
df[['dias_seguimiento', 'anos_seguimiento']].head()

KeyError: 'dias_seguimiento'

### 11. Transformación 3: Mapeo de valores a texto explícito
Se transforman las columnas de género y estado vital a texto claro (`Masculino/Femenino` y `Fallecido/Sobreviviente`) para facilitar la interpretación del dataset.

In [ ]:
# Crear variables categóricas descriptivas usando .loc
df.loc[:, 'genero'] = df['es_hombre'].map({True: 'Masculino', False: 'Femenino'})
df.loc[:, 'estado_vital'] = df['fallecido'].map({1: 'Fallecido', 0: 'Sobreviviente'})

# Mostrar la comparación de las columnas transformadas
df[['es_hombre', 'genero', 'fallecido', 'estado_vital']].head()

   es_hombre     genero  fallecido estado_vital
0       True  Masculino          1    Fallecido
1       True  Masculino          1    Fallecido
2       True  Masculino          1    Fallecido
3       True  Masculino          1    Fallecido
4      False   Femenino          1    Fallecido

### 12. Transformación 4: Agrupamiento y resumen estadístico por grupo
Se agrupan los datos según el `estado_vital` del paciente para calcular los promedios de los principales biomarcadores clínicos.

In [ ]:
# Agrupamiento por estado vital y cálculo de promedios
df_resumen = df.groupby('estado_vital').agg({
    'edad': 'mean',
    'fraccion_eyeccion': 'mean',
    'creatinina_serica': 'mean',
    'concentracion_plaquetas': 'mean'
}).rename(columns={
    'edad': 'Edad Promedio',
    'fraccion_eyeccion': 'Fracción Eyección (%)',
    'creatinina_serica': 'Creatinina Promedio',
    'concentracion_plaquetas': 'Plaquetas Promedio'
}).reset_index()

df_resumen

,estado_vital,Edad Promedio,Fracción Eyección (%),Creatinina Promedio,Plaquetas Promedio
0,Fallecido,65.208333,33.46875,1.835833,256381.044792
1,Sobreviviente,58.758621,40.26601,1.184877,266657.489901